---
name: Parse-Syslog-Mail
version: 0.01
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Parse mailer logs from syslog
license: perl
requires:
  Parse::Syslog: 0
  Test::More: 0
provides:
  Parse::Syslog::Mail:
    file: lib/Parse/Syslog/Mail.pm
    version: 0.01
generated_by: Module::Build version 0.2609
